import Head from 'next/head';
import { ReactElement } from 'react';

interface HeadProps {
  title?: string;
}

export default function HeadTag({ title = 'GraphQL Sample' }: HeadProps): ReactElement {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
