import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { useAnilistQuery } from 'services/apollo/anilist/queries';

export default function Home({ countries }) {
  const { data } = useAnilistQuery('page', {variables: {customVar: 'asdf'}});
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <a href="/animes">Animes</a>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  // const { data } = await client.query({
  //   query: GET_COUNTRIES,
  // });
  
  return {
    props: {
      // countries: data.countries,
      countries: null
    },
  };
}

