import Head from 'next/head';
import { useAnilistQuery } from 'services/apollo/anilist/queries';

export default function Home() {
  const { data } = useAnilistQuery('page', { variables: { customVar: 'asdf' } });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <a href="/animes">Animes</a>
        <div>{JSON.stringify(data)}</div>
      </main>
    </div>
  );
}

// export const getServerSideProps: GetServerSideProps = async () =>
//   const { data } = await client.query({
//     query: GET_COUNTRIES,
//   });

//   ({
//     props: {
//       countries: data.countries,
//       countries: null,
//     },
//   });
